#!/usr/bin/env node

/**
 * Build script for CodeMirror bundle used in the playground.
 *
 * Usage: node tools/playground/build_codemirror.mjs
 *
 * This script bundles CodeMirror packages into a single file for the playground.
 * Dependencies are declared in tools/playground/package.json.
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "../..");
const outputFile = path.resolve(__dirname, "libs/codemirror.bundle.js");

console.log("Bundling CodeMirror...");

const entryContent = `
// CodeMirror bundle for OWL Playground
// Auto-generated by tools/build_codemirror.mjs

export { Annotation, Compartment, EditorState, Transaction, StateEffect, StateField, Prec, Facet } from "@codemirror/state";
export { EditorView, keymap, drawSelection, dropCursor, crosshairCursor, rectangularSelection, highlightActiveLine, highlightActiveLineGutter, highlightSpecialChars, lineNumbers } from "@codemirror/view";
export { defaultHighlightStyle, syntaxHighlighting, bracketMatching, foldGutter, indentOnInput, indentUnit, syntaxTree } from "@codemirror/language";
export { autocompletion, acceptCompletion, startCompletion, completeFromList, ifIn, ifNotIn, CompletionContext, snippet, snippetCompletion } from "@codemirror/autocomplete";
export { indentLess, indentMore, indentWithTab } from "@codemirror/commands";
export { javascript } from "@codemirror/lang-javascript";
export { css } from "@codemirror/lang-css";
export { xml } from "@codemirror/lang-xml";
export { markdown } from "@codemirror/lang-markdown";
export { oneDark } from "@codemirror/theme-one-dark";
export { basicSetup } from "codemirror";
export { abbreviationTracker, expandAbbreviation } from "@emmetio/codemirror6-plugin";
`;

const tempEntry = path.resolve(rootDir, "temp_codemirror_entry.mjs");
fs.writeFileSync(tempEntry, entryContent);

try {
  const esbuild = await import("esbuild");

  await esbuild.build({
    entryPoints: [tempEntry],
    outfile: outputFile,
    bundle: true,
    format: "esm",
    minify: true,
  });

  console.log(`\nBundle written to: ${outputFile}`);

  // Show file size
  const stats = fs.statSync(outputFile);
  console.log(`Bundle size: ${(stats.size / 1024).toFixed(1)} KB`);
} finally {
  // Clean up temp file
  fs.unlinkSync(tempEntry);
}

console.log("\nDone!");
